AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Resume Health Checker - FastAPI on AWS Lambda

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.12

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - staging
      - prod
  OpenAIApiKey:
    Type: String
    NoEcho: true
    Description: OpenAI API Key
  StripePaymentUrl:
    Type: String
    Description: Stripe Payment URL
  StripeSuccessToken:
    Type: String
    NoEcho: true
    Description: Stripe Success Token

Resources:
  ResumeHealthCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'resume-health-checker-api-${Environment}'
      CodeUri: .
      Handler: lambda_handler_monolith.lambda_handler
      Runtime: python3.12
      Timeout: 30
      MemorySize: 1024
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIApiKey
          STRIPE_PAYMENT_URL: !Ref StripePaymentUrl
          STRIPE_PAYMENT_SUCCESS_TOKEN: !Ref StripeSuccessToken
          ENVIRONMENT: !Ref Environment
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootApiGateway:
          Type: Api
          Properties:
            Path: /
            Method: ANY
    Metadata:
      BuildMethod: python3.12

# CloudWatch Log Group will be created automatically by Lambda

Outputs:
  ApiGatewayUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiGatewayUrl"
  
  LambdaFunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt ResumeHealthCheckerFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-LambdaFunctionArn"